# -*- coding: utf-8 -*-
"""matrix_chain_pract-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1galcygmF6mPvOqtAOeW6j8UGcRoaL_yX
"""

def matrix_chain_order(p):
    n = len(p) - 1

    # Create DP matrix
    dp = [[0 for _ in range(n)] for _ in range(n)]

    # Chain length
    for length in range(2, n + 1):

        for i in range(n - length + 1):
            j = i + length - 1

            dp[i][j] = float('inf')

            # Try every possible split
            for k in range(i, j):
                cost = (
                    dp[i][k]
                    + dp[k + 1][j]
                    + p[i] * p[k + 1] * p[j + 1]
                )

                if cost < dp[i][j]:
                    dp[i][j] = cost

    return dp


# Input
n = int(input("Enter number of matrices: "))

print("Enter dimensions:")

p = list(map(int, input().split()))

if len(p) != n + 1:
    print("Error: Enter exactly", n + 1, "dimensions.")
else:
    dp = matrix_chain_order(p)

    print("\nDP Matrix:")

    for row in dp:
        print(row)

    print("\nMinimum number of scalar multiplications:",
          dp[0][n - 1])